<a href="https://colab.research.google.com/github/ruchashastri/daa/blob/main/ML_assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Importing Packages
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn import datasets

In [4]:
# Loading Dataset
data = datasets.load_iris()
print(data)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [6]:
x = data.data
y = data.target

In [7]:
z = data.target_names
print(data.feature_names)
print(x[0])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[5.1 3.5 1.4 0.2]


In [8]:
# Split Dataset
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [9]:
# Data Shape
print(x_train.shape)
print(x_test.shape)

(105, 4)
(45, 4)


In [10]:
# Building the Model
model= Sequential()
model.add(Dense(100,input_shape=(4,), activation="relu"))
model.add(Dense(3, activation='softmax'))

In [11]:
# Compile the Model
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])

In [12]:
# Fit the Model
model.fit(x_train,y_train, epochs=20)

Epoch 1/20
4/4 [==============================] - 1s 7ms/step - loss: 1.6687 - accuracy: 0.3429
Epoch 2/20
4/4 [==============================] - 0s 4ms/step - loss: 1.3425 - accuracy: 0.3429
Epoch 3/20
4/4 [==============================] - 0s 4ms/step - loss: 1.1492 - accuracy: 0.3429
Epoch 4/20
4/4 [==============================] - 0s 4ms/step - loss: 1.0352 - accuracy: 0.3048
Epoch 5/20
4/4 [==============================] - 0s 4ms/step - loss: 1.0006 - accuracy: 0.3048
Epoch 6/20
4/4 [==============================] - 0s 4ms/step - loss: 0.9553 - accuracy: 0.4762
Epoch 7/20
4/4 [==============================] - 0s 4ms/step - loss: 0.9106 - accuracy: 0.6095
Epoch 8/20
4/4 [==============================] - 0s 6ms/step - loss: 0.8734 - accuracy: 0.6381
Epoch 9/20
4/4 [==============================] - 0s 5ms/step - loss: 0.8438 - accuracy: 0.6667
Epoch 10/20
4/4 [==============================] - 0s 3ms/step - loss: 0.8161 - accuracy: 0.6667
Epoch 11/20
4/4 [======================

In [13]:
# Evaluate the Model
model.evaluate(x_test, y_test)

2/2 [==============================] - 0s 8ms/step - loss: 0.6129 - accuracy: 0.8444


[0.6129045486450195, 0.8444444537162781]

In [14]:
# Predict for the first 10 Observations
pred=model.predict(x_test[:10])
print(pred)

1/1 [==============================] - 0s 78ms/step
[[0.7937788  0.12383414 0.08238717]
 [0.7170988  0.16153252 0.12136871]
 [0.69533515 0.17169216 0.13297267]
 [0.64687407 0.20236993 0.15075599]
 [0.73348904 0.15255181 0.1139591 ]
 [0.05278878 0.4250979  0.52211326]
 [0.06607506 0.3947403  0.5391846 ]
 [0.08069713 0.43332925 0.4859735 ]
 [0.07992914 0.38960233 0.5304686 ]
 [0.65468776 0.1973482  0.14796402]]


In [15]:
p=np.argmax(pred, axis=1)
print(p)
print(y_test[:10])

[0 0 0 0 0 2 2 2 2 0]
[0 0 0 0 0 2 2 2 2 0]


In [18]:
# Prediction Result
for i in p:
    print("Predicted-Class: {}, Name: {}".format(i,z[i]))

Predicted-Class: 0, Name: setosa
Predicted-Class: 0, Name: setosa
Predicted-Class: 0, Name: setosa
Predicted-Class: 0, Name: setosa
Predicted-Class: 0, Name: setosa
Predicted-Class: 2, Name: virginica
Predicted-Class: 2, Name: virginica
Predicted-Class: 2, Name: virginica
Predicted-Class: 2, Name: virginica
Predicted-Class: 0, Name: setosa
